name: perfect_freehand
version: 2.0.0
description: Draw perfect pressure-sensitive freehand lines. A set of functions for turning input points into a polygon of outline points.
homepage: https://adil192.github.io/perfect_freehand/
repository: https://github.com/adil192/perfect_freehand
documentation: https://github.com/adil192/perfect_freehand
issue_tracker: https://github.com/adil192/perfect_freehand/issues
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
